addons:
  sonarcloud:
    organization: "henryssondaniel-github"
    token:
      secure: $SONAR_TOKEN
dist: xenial
language: python
matrix:
  include:
    - python: "3.4"
      env: FULL_RUN=true
    - python: "3.5"
      env: FULL_RUN=false
    - python: "3.6"
      env: FULL_RUN=false
    - python: "3.7"
      env: FULL_RUN=false
    - python: "3.8"
      env: FULL_RUN=false
    - python: "nightly"
      env: FULL_RUN=false
    - python: "pypy3.5"
      env: FULL_RUN=false
script:
  - if [ "$FULL_RUN" == "false" ]; then python -m unittest discover tests; fi
  - if [ "$FULL_RUN" != "false" ]; then coverage run -m unittest discover tests; coverage xml -i; sonar-scanner; fi