addons:
  sonarcloud:
    organization: "henryssondaniel-github"
    token:
      secure: $SONAR_TOKEN
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
  - "pypy3.5"
script:
  - python -m unittest
  - sonar-scanner